### ISSUE TITLE
The infoBox setting in map settings isn't honored.

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#781] opened 2021-04-29 11:22 UTC
**Describe the bug**
The infoBox setting in map settings isn't honored.

When you've entered html or markdown in infoBox setting....
![1](https://user-images.githubusercontent.com/73874338/116541764-2c111f80-a8ec-11eb-8697-76397887a8d8.png)

... the code that reads the value has been commented in ConfigMapper.js 
https://github.com/hajkmap/Hajk/blob/b92947ae05bc32a00aa7faf9a87f8512fd0ba504/new-client/src/utils/ConfigMapper.js#L123
![2](https://user-images.githubusercontent.com/73874338/116542088-8a3e0280-a8ec-11eb-9f7b-a58fa11730e9.png)

.... and the popup will fail to use the html/markdown in map settings.
https://github.com/hajkmap/Hajk/blob/b92947ae05bc32a00aa7faf9a87f8512fd0ba504/new-client/src/components/FeatureInfo/FeatureInfoContainer.js#L231
![3](https://user-images.githubusercontent.com/73874338/116542304-d12bf800-a8ec-11eb-97f4-b88808a396a7.png)

**Suggestion**
Uncomment the commented line.
One problem could be that this could override html/markdown if someone has unused infoBox settings in map settings.
This is why I've added the label (needs-discussion)...............

**Comment by jacobwod** [comment] 2021-04-29 11:46
Hmm… I tried this out instantly (as we're using overriding of infobox/visibleAtStart _a lot_ in our maps), and I could not reproduce your problem.

I'm on **current `master`** and using the Node backend. 

**No override:**
![Skärmavbild 2021-04-29 kl  13 44 09](https://user-images.githubusercontent.com/110222/116545840-31bd3400-a8f1-11eb-9530-dd13c13f5dba.png)
![Skärmavbild 2021-04-29 kl  13 44 31](https://user-images.githubusercontent.com/110222/116545825-2d911680-a8f1-11eb-84f3-bc80b5c7428a.png)

**With override:**
![Skärmavbild 2021-04-29 kl  13 43 46](https://user-images.githubusercontent.com/110222/116545880-400b5000-a8f1-11eb-9373-9147382fba4e.png)
![Skärmavbild 2021-04-29 kl  13 43 57](https://user-images.githubusercontent.com/110222/116545883-413c7d00-a8f1-11eb-8e55-3d0d9095be9f.png)

**Comment by jesade-vbg** [comment] 2021-04-29 11:53
Ok, I think it's because I have a grouplayer in Geoserver and FeatureInfo does not handle this today I think. So uncommenting solved this.

**Comment by jacobwod** [comment] 2021-04-29 11:58
If it's a GeoServer Layer Group, then it looks the same as regular layer in Hajk's admin. Are you saying that specifying infobox in the "first" tab in admin works as expected for your given layer group, but you can't override it in the "fourth" tab, in map settings?

**Comment by jesade-vbg** [comment] 2021-04-29 12:58
The only way I can display html is by uncommenting in ConfigMapper. FeatureInfo can't get html the other ways as Geoserver returns features for layers the does not exist i Hajk. So it can't map to correct infobox-data.

**Comment by jacobwod** [comment] 2021-04-29 13:00
I'm trying to reproduce…

**Comment by jesade-vbg** [comment] 2021-04-30 07:47
Status: We have established that this indeed is a bug. Why the needed code is commented.... we don't know. What is the consequences if we uncomment.... not sure. How we proceed.... is not decided.

**Comment by Hallbergs** [comment] 2021-04-30 09:35
Haha wonderful....

**Comment by jesade-vbg** [comment] 2021-05-04 07:34
I made a decision. Uncommented and pushed the commit.
https://github.com/hajkmap/Hajk/commit/332bb04a9b3841b5f497526b7ea916b13c6c1369

Perhaps we should raise a flag the next code meeting.

**Comment by jacobwod** [comment] 2021-05-04 09:05
Good idea, can you write it down on the upcoming meeting agenda so it won't be forgotten?

**Comment by Hallbergs** [comment] 2021-11-23 08:09
This was closed as of 3.7.0!

**Closed by Hallbergs** 2021-11-23 08:09 UTC
Labels: bug, needs-discussion
