### ISSUE TITLE
Search layer visible even if it is locked by AD

### ISSUE THREAD

**Issue by persoderstrom** [hajkmap/Hajk#748] opened 2021-04-09 13:52 UTC
If you have activated AD lookup and locked all search layers by AD groups,then a user not granted access will still see all layers. This only occurs when the user does not have access to any of the search layer.

**To Reproduce**
1. Activate AD lookup (in .env in NodeJS backend)
2. In admin, configure two search layers and lock all with an AD group that the tester is not a member of.
3. Open map in client
4. In search tool choose "Sökinställningar" - "Begränsa sökkällor"
5. The search layers are there

**Expected behavior**
No search layers 

**Screenshots**
![image](https://user-images.githubusercontent.com/1893510/114189868-f6ab8e80-994a-11eb-9016-6ef8b6136525.png)

![image](https://user-images.githubusercontent.com/1893510/114190024-23f83c80-994b-11eb-9e46-a8265a4b3018.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Backend: NodeJS, api/v1. (Not tested in .Net/IIS backend)
   Tested with a fresh download from master. 
   
**Additional context**
The search options.layers in the washed map configuration is correct empty, so I think the problem might be in the new-client AppModel.js.

**Comment by jacobwod** [comment] 2021-04-12 06:27
Interesting, but I could not replicate:
![Skärmavbild 2021-04-12 kl  08 24 31](https://user-images.githubusercontent.com/110222/114349903-c6413b80-9b68-11eb-90f2-0244924354c9.png)
![Skärmavbild 2021-04-12 kl  08 24 37](https://user-images.githubusercontent.com/110222/114349908-c80aff00-9b68-11eb-9ca1-fa4996b78eae.png)


Since you're on the NodeJS backend anyway, can you please try adding `experimentalNewApi: true` to your `appConfig.json` and see if this changes anything?

**Comment by persoderstrom** [comment] 2021-04-12 06:57
I made these tests:

  "mapserviceBase": "http://localhost:3002/api/v1",
  "experimentalNewApi": **false**,
  search-tool options.layers: []
  => the search layers **are shown**
  
  "mapserviceBase": "http://localhost:3002/api/v1",
  "experimentalNewApi": **true**, (forces the api to api/v2)
  search-tool options.layers: []
  => the search layers are **NOT** shown
  
  "mapserviceBase": "http://localhost:3002/api/v2",
  "experimentalNewApi": **true**,
  search-tool options.layers: []
  => the search layers are **NOT** shown

**Comment by persoderstrom** [comment] 2021-04-12 07:15
I think that this is a result of that if you don't check any search service as searchable then all WFS layers become searchable, as stated in Admin.

**Comment by jacobwod** [comment] 2021-04-12 07:35
Yes, and while `experimentalNewApi` "washes" the contents of `layers` (that contain `wfslayers` which are our search services), the "old API" returns the entire contents of `layers.json`. And the client mistakenly looks for what's inside `layers.wfslayers` instead of `mapconfig.tools.filter(t => t.name === 'search').options.layers`. 

**In my option, the new behaviour is better: if nothing was selected in admin, nothing should be available.** 

The only question is whether we should do something about this now or just let everyone else migrate to the Node and make `experimentalNewApi` true by default. Or do a fix in the search model to grab services from `mapconfig` instead of `layers`. What's @Hallbergs's opinion on this?

**Comment by Hallbergs** [comment] 2021-04-12 10:28
Hm. I guess the best solution would be to update the client so that the client delivers the same results with whatever backend we use. I agree that if we don't select any sources in admin, we shouldn't fetch all sources.

**Comment by jacobwod** [comment] 2021-04-16 08:39
In a perfect world, both backends should deliver the same results given the same input files. But I guess that adding the wash function to the .NET backend isn't something anyone would like to do? Reaching out to @maan002 and @jesade-vbg, as you use the .NET backend as well as AD functionality, hence **you are affected by this bug**.

**Comment by jacobwod** [comment] 2021-04-16 08:44
On the other hand, given the results of @perosoderstrom's test:
```
"mapserviceBase": "http://localhost:3002/api/v1",
"experimentalNewApi": false,
search-tool options.layers: [] in the returned map cofig
=> the search layers are shown
```

Even the Node backend will return unwashed contents of `layers.json` when using the non-experimental, not consolidated loading (v1). **The problem is that we do expose a lot of things in `layers`, but don't use them later on. That's precisely the motivation behind my fix (the v2 loading).** But the legacy (v1) has always worked like that and we should perhaps leave it as-is and **fix the client (as proposed by @Hallbergs) by rendering only those search sources that exist in the search tool's `options.layers` array** which is correctly empty in all cases. What you say?

**Comment by persoderstrom** [comment] 2021-04-16 08:54
There is a wash function for search layers in .NET backend (ConfigController.cs - FilterSearchLayersByAD). It works similar to new-backend - v1. 
I am about to add a FilterEditLayersByAD to wash edit layers too. And as suggested, will only expose edit services in client that are checked. It is in the branch ad-edit-layers. (This branch is messed up, but a fix is on its way)

**Comment by jacobwod** [comment] 2021-04-16 08:58
@persoderstrom That's not related to the wash function I'm thinking of. No matter the washing inside `map_1.json`, when no search layers are selected, the `layers.json` file still contains _all_ search sources that has been setup in admin (look at the `wfslayers` array inside `layers.json`). 

In v2, the contents of `wfslayers` is "washed", i.e. unused search sources (and all other types of layers) are actually removed from the response and never make it to the client.

**Comment by persoderstrom** [comment] 2021-04-16 09:05
Yes. .NET and v1 works the same and returns layers with wfslayers. 
But the search or edit client should not default to wfslayers or wfstlayers if no layers are checked in admin.

**Comment by jacobwod** [comment] 2021-04-16 09:13
Exactly, that's my point, and that's what @Hallbergs proposed: to remove stuff, client-side.

**Comment by jacobwod** [comment] 2021-04-16 09:13
I'm looking at SearchModel at the moment.

**Comment by persoderstrom** [comment] 2021-04-16 09:22
Fallback to wfslayers if no search layers are checked is done in AppModel.js

**Comment by jacobwod** [comment] 2021-04-16 09:27
Exactly, here's the root cause:
```
if (searchTool) {
      if (searchTool.options.layers === null) {
        searchTool.options.sources = layers.wfslayers;
      } else {
        if (
          searchTool.options.layers &&
          searchTool.options.layers.length !== 0
        ) {
          let wfslayers = this.overrideGlobalSearchConfig(searchTool, layers);
          searchTool.options.sources = wfslayers;
          layers.wfslayers = wfslayers;
        } else {
          searchTool.options.sources = layers.wfslayers;
        }
      }
    }
```

**Comment by jacobwod** [comment] 2021-04-16 09:28
I propose that we _always_ run the `overrideGlobalSearchConfig`, as it's the correct behaviour, and _never_ set `sources` to the entire `wfslayers`.

**Comment by Hallbergs** [comment] 2021-04-16 09:32
I agree. Always using `overrideGlobalSearchConfig` feels like the best way forward.

**Comment by jacobwod** [comment] 2021-04-16 12:45
OK. So I've commited a fix and this _can_ be closed once merged. But we must inform, especially in the changelog, as I can see this as a breaking change for some setups. Should we still aim for pushing it to 3.6 on Monday?

**Comment by Hallbergs** [comment] 2021-04-16 12:51
Perfect!! In my opinion we should include it in 3.6. Perfect opportunity to see if the testing strategy works.

**Closed** 2021-04-19 07:09 UTC
