### ISSUE TITLE
Handling documents inside a folder for DocumentManager2.0

### ISSUE THREAD

**Issue by Anyou22** [hajkmap/Hajk#1229] opened 2022-11-02 11:11 UTC
**Describe the bug**
Handling documents inside a folder.

In the "Document Manager" tool, there is a possibility to create many different types of "Story Maps" (Berättarkartor).
In order to have a well structured maps , we would like to develop the function further so that the json files that are currently created for the "Document Manager" can be organized in different folders based on which "Story Map" the documents belong to.
In order to organize the json documents which are used for the "Dokumenthanteraren 2.0" into  "Story Maps" more  than once, it would be good if the used json documents can be structured on the server (... \ App_Data \ documents) under different folders based on which "Story Map" they belong to.

**To Reproduce**

Under the tab for "Document Manager 2.0" there is a start function called "General document settings".
This function can be replaced to take a second place and instead set the function which creates "story map" in the first place.
As soon as the user creates a "Story Map", so automatically a new file will be created on the server under the directory ...\App_Data\documents, e.g. (...\App_Data\documents\narratormapXXX). 
In this folder, all the created json documents will be placed in the specific "Story Map".

# StoryMap: Berättarkartan

**Screenshots**
![image](https://user-images.githubusercontent.com/113990946/199474798-6f3611b7-b5da-4f6c-a135-1e834eea94bd.png)

**Comment by jacobwod** [comment] 2022-11-02 12:22
Besides, looks like a duplicate of https://github.com/hajkmap/Hajk/issues/881.

**Comment by Anyou22** [comment] 2022-11-02 12:26
Thank you @jacobwod ! Nicklas didn't mention anyhthing about #881. Do I need to delete the #1229 issue? so we can keep on #881!

**Comment by jacobwod** [comment] 2022-11-02 14:13
Duplicate of #881.

**Closed by jacobwod** 2022-11-02 14:13 UTC
Labels: rejected:incomplete
