### ISSUE TITLE
Min/max zoom: disable warning snackbars on some occasions

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#944] opened 2021-12-02 07:57 UTC
If you have lots of active layers at start that's not visible due to current zoom, Hajk queues and spits out multiple snackbars.
In one of our maps where we noticed this, it produces 12 snackbars... not very useful. This also happens when you zoom in and out.

I would like to be able to disable snackbars at start and when zooming in/out.
This would only leave the snackbars intact when toggling layers, which I feel is enough.

Suggestion 1:
A checkbox in admin
[x] Only show warning snackbars when toggling layers.

Snackbars:
![minmaxzoom-warning](https://user-images.githubusercontent.com/73874338/144380121-8762eb73-9749-464a-99cc-24a933553ced.jpg)

Any other suggestions?

**Comment by Hallbergs** [comment] 2021-12-02 08:09
I like it! 

If you toggle a layer-group with several layers that won't show with the current zoom setting you'll get several snacks too, right? Maybe we could combine the messages to one message, stating that several layers aren't shown? (If we want to go even further we could also include a info-button which could show which layers that are hidden)?

**Comment by jesade-vbg** [comment] 2021-12-02 08:21
I'm not sure that it works for layer-groups.
Heres more issues regarding this functionality. #756, #810.

It's all good ideas you have @Hallbergs. 

Maybe we could keep these issues separate? I really need to be able to disable the snackbars, kind of yesterday :)

**Comment by Hallbergs** [comment] 2021-12-02 09:08
Ah i see. Yes ofc!

**Comment by jacobwod** [comment] 2021-12-09 07:09
Hi @jesade-vbg! I just took a look in `develop` where this is merged and it seems like there's some unwanted behaviour. **The Snackbar will "flash" briefly on page load.** The flash is too short to be useable for the user, but I'm not sure what your intention was in this case: to show it normally on page load (5 seconds) or not show it at all?

https://user-images.githubusercontent.com/110222/145350211-99ff4c5a-a8f9-4a67-bb6b-01e6822fea28.mov

**Comment by jesade-vbg** [comment] 2021-12-09 07:17
OK, thats not intended. It should show as before (pre change) or not at all at page load.
I guess it should be visible in your case?

I've tested it allot but never with one snack. I'll look into it now.

**Comment by jesade-vbg** [comment] 2021-12-09 07:40
@jacobwod This is weird, I cant recreate the problem.
https://user-images.githubusercontent.com/73874338/145354002-fb1fbdf7-9006-41e5-ac49-7f5326c53a78.mp4

**Comment by jacobwod** [comment] 2021-12-09 07:50
I checked the settings and it's not what we expected it to be, so I understand that you couldn't find it easily. 

What you need to do is **add a layer with min/max limitations, and set the maps start zoom so that we exceed the layer's limitations, and _also_ make sure that you _don't have visible at start_**. 

### Works as expected with `visibleAtStart`
When I turn on visible at start, it acts as expected:
![Skärmavbild 2021-12-09 kl  08 46 42](https://user-images.githubusercontent.com/110222/145355173-29bd841a-1ac3-4615-9526-7b6ed97119c5.png)

https://user-images.githubusercontent.com/110222/145355136-245ad77c-6380-4658-93c3-a30d6f4eaad1.mov

### Unexpected behaviour with `visibleAtStart` turned off
But turn off the visible at start setting and you get the flashing behaviour:
![Skärmavbild 2021-12-09 kl  08 46 39](https://user-images.githubusercontent.com/110222/145355250-92b7b528-81c8-4566-ad77-bd985885e063.png)

https://user-images.githubusercontent.com/110222/145355372-aeb57b1b-0722-4f8a-bb78-27bd56a56c9c.mov

**Comment by jesade-vbg** [comment] 2021-12-09 07:58
That was it, I can see it now. It flashes by for about 200ms on my computer.
https://user-images.githubusercontent.com/73874338/145356453-6e664c7b-c2d6-4a24-8e8a-09ac73671785.mp4

Proceeding....

**Comment by jacobwod** [comment] 2021-12-09 08:04
Yeah, that's it. 😢

**Comment by jesade-vbg** [comment] 2021-12-09 08:08
Pushed a fix. Zoomcheck should not be triggered at start.

**Comment by jacobwod** [comment] 2021-12-09 08:33
I can confirm that the fix works as intended, good job. 👍

**Comment by jesade-vbg** [comment] 2021-12-09 09:05
Great, and good find! 👍 Sorry for the inconvenience

**Comment by jacobwod** [comment] 2021-12-09 09:25
No worries! 😄

**Closed** 2021-12-15 09:01 UTC
Labels: plugin:layerswitcher, new-feature, idea
