### ISSUE TITLE
Items disappear at certain zoom levels

### ISSUE THREAD

**Issue by gregor-shapiro** [hajkmap/Hajk#892] opened 2021-11-05 08:32 UTC
**Describe the bug**
At certain zoom levels the street numbers of buildings are not shown for some buildings. They reappear at other zoom levels.
**To Reproduce**

1. Go to 'karta.halmstad.se', 
2. Click on 'Sök...' Search for "Fogdegatan 44"
3. Zoom in  and out with scroll wheel or the [+], [-] buttons
4. See the [44] on the house appear and disappear

**Expected behavior**
The number should only disappear when it would be too small to be useful but it should be visible at all closer ranges

**Screenshots**
![image](https://user-images.githubusercontent.com/26760444/140480823-4c8ec676-36df-4cd7-8167-05f9f839c2c9.png)
![image](https://user-images.githubusercontent.com/26760444/140480871-4b8c693b-573c-4f29-be11-fa0ac327fa64.png)
![image](https://user-images.githubusercontent.com/26760444/140480931-d84cacb1-f550-463e-90ab-8d635ca9ce08.png)

**Desktop (please complete the following information):**

- OS: Windows10
- Browser Brave 
- Version Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
It could be a font size thing??? It does happen between  zoom factors with different font sizes 
I am just a user and not a coder...

**Comment by FredrikEkstrom79** [comment] 2021-11-05 10:20
The background you use is distributed from Lantmäteriet, we only use it in our map service. It is Lantmäteriet that has set the individual zoom levels for when an object type (buildings, road, labels ...) is visible on the map or not.

It is beyond our control to change this as it is right now.

**Comment by gregor-shapiro** [comment] 2021-11-05 10:44
Can you submit this as a bug to Lantmäteriet?
/Gregor

**Comment by FredrikEkstrom79** [comment] 2021-11-05 10:54
It's not a bug. It's just that they've chosen these zoom levels for their map.
If it does not suit your needs it is a shame but it is unfortunately the way it is.

**Comment by Hallbergs** [comment] 2021-11-05 11:32
As stated above, this is not a Hajk related issue. Closing!

**Closed by Hallbergs** 2021-11-05 11:32 UTC

**Comment by gregor-shapiro** [comment] 2021-11-05 12:06
Disappearing and reappearing house numbers for certain buildings but not
others sure looks like a bug to me! Certainly unexpected (and I suspect
unwanted) behavior!
