### ISSUE TITLE
Layer groups in backgrounds panel

### ISSUE THREAD

**Issue by JakubPelka** [hajkmap/Hajk#1042] opened 2022-03-16 12:10 UTC
Problem:
Nowadays all backgrounds are visible as seperate layers. And if we have a lot of them it is / might be messy. For example while having more ortophotos, and terrain data, etc.

Solution:
Make it possible to create groups of background layers as it is now in normal layer panel. So all Ortophotos could be grouped and stored in on category. Topographical data like lutning, terräng skuggning, belysnig etc. in another group - etc.

**Comment by jacobwod** [comment] 2022-06-28 08:27
Duplicate of #194

**Closed by jacobwod** 2022-06-28 08:27 UTC
